---

- hosts: lokalno
  become: false
  tasks:

  - name: skidanje fajla sa neta
    delegate_to: localhost
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/nikolalakic/pajaPOC/master/test_skripta.sh
      dest: /home/$USER/test_skripta.sh
      mode: '0755'
      
  - name: Kopiranje skripte na target
    raw: scp -P 51821 nikolal@192.168.1.10:/home/$USER/test_skripta.sh /home/$USER/
  
  - name: Pokretanje skripte
    raw: /usr/bin/bash /home/$USER/test_skripta.sh
